# Generated by Django 4.0.6 on 2022-07-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
