# Generated by Django 4.0.6 on 2022-07-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_created_at_task_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='body',
        ),
    ]
